name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    uses: davorg/github-worksflows/.github/workflows/cpan-test.yml

  coverage:
    uses: davorg/github-worksflows/.github/workflows/cpan-coverage.yml

