name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    uses: davorg/github_workflows/.github/workflows/cpan-test.yml@main

  coverage:
    uses: davorg/github_workflows/.github/workflows/cpan-coverage.yml@main

